//! `Cargo.lock` bridge: adapter and merge (spec §4.4, §12 M3, ADR 0013).
//!
//! The M3 acceptance line "`Cargo.lock` concurrent dependency additions merge
//! cleanly" is `concurrent_dependency_additions_merge_cleanly` (table) and
//! `real_lockfile_concurrent_additions_reproduce_it` (proptest over the real
//! fixtures, which are cargo.git and hord lockfiles written by Cargo).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

use hord_core::{NodeKind, RepoPath};
use hord_lang::{LangAdapter, NodeTree};
use hord_lang_rust::{
    CargoLockAdapter, CargoLockConflict, CargoLockMergeError, is_cargo_lock, merge_cargo_lock,
};
use hord_lang_toml::TomlAdapter;
use hord_lang_toml::merge::{ConflictKind, TomlConflict};
use proptest::prelude::*;

const REGISTRY: &str = "registry+https://github.com/rust-lang/crates.io-index";
const HEADER: &str = "# This file is automatically @generated by Cargo.\n\
                      # It is not intended for manual editing.\n\
                      version = 4\n\n";

fn fixtures() -> Vec<(String, String)> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/lock");
    let mut out: Vec<_> = fs::read_dir(&dir)
        .expect("testdata/lock")
        .map(|e| e.expect("entry").path())
        .filter(|p| p.extension().is_some_and(|e| e == "lock"))
        .map(|p| {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            (name, fs::read_to_string(&p).expect("read"))
        })
        .collect();
    out.sort();
    assert!(out.len() >= 3, "expected the real lockfile fixtures");
    out
}

fn merge(base: &str, ours: &str, theirs: &str) -> Result<String, CargoLockMergeError> {
    merge_cargo_lock(base.as_bytes(), ours.as_bytes(), theirs.as_bytes())
        .map(|b| String::from_utf8(b).expect("utf-8"))
}

/// Merge both ways and require the same answer (spec §11.1 commutativity).
fn merge_both(base: &str, ours: &str, theirs: &str) -> Result<String, Vec<CargoLockConflict>> {
    let a = merge(base, ours, theirs);
    let b = merge(base, theirs, ours);
    match (a, b) {
        (Ok(a), Ok(b)) => {
            assert_eq!(a, b, "merge is not commutative");
            Ok(a)
        }
        (Err(CargoLockMergeError::Conflict(a)), Err(CargoLockMergeError::Conflict(b))) => {
            assert_eq!(a, b, "conflicts are not commutative");
            Err(a)
        }
        (a, b) => panic!("asymmetric merge: {a:?} vs {b:?}"),
    }
}

/// A registry package block as Cargo writes it.
fn pkg(name: &str, version: &str, deps: &[&str]) -> String {
    let mut s = format!(
        "[[package]]\nname = \"{name}\"\nversion = \"{version}\"\nsource = \"{REGISTRY}\"\n\
         checksum = \"{:0>64}\"\n",
        format!("{name}{version}").len()
    );
    push_deps(&mut s, deps);
    s
}

/// A path (workspace) package block.
fn root(name: &str, deps: &[&str]) -> String {
    let mut s = format!("[[package]]\nname = \"{name}\"\nversion = \"0.1.0\"\n");
    push_deps(&mut s, deps);
    s
}

fn push_deps(s: &mut String, deps: &[&str]) {
    if !deps.is_empty() {
        s.push_str("dependencies = [\n");
        for d in deps {
            s.push_str(&format!(" \"{d}\",\n"));
        }
        s.push_str("]\n");
    }
    s.push('\n');
}

/// Join package blocks into a lockfile (Cargo drops the final blank line).
fn lockfile(blocks: &[String]) -> String {
    let mut s = format!("{HEADER}{}", blocks.concat());
    while s.ends_with("\n\n") {
        s.pop();
    }
    s
}

fn def_names(tree: &NodeTree, kind: &str) -> Vec<String> {
    tree.iter()
        .filter(|(_, n)| n.kind.as_str() == kind)
        .filter_map(|(_, n)| n.name.as_ref().map(ToString::to_string))
        .collect()
}

// ---------------------------------------------------------------- adapter

#[test]
fn matches_only_cargo_lock() {
    let a = CargoLockAdapter;
    let path = |s| RepoPath::from_str(s).unwrap();
    assert!(a.matches(&path("Cargo.lock"), &[]));
    assert!(a.matches(&path("crates/foo/Cargo.lock"), &[]));
    assert!(!a.matches(&path("Cargo.toml"), &[]));
    assert!(!a.matches(&path("Cargo.lock.orig"), &[]));
    assert!(!a.matches(&path("cargo.lock"), &[]));
    assert!(!a.matches(&path("foo/Cargo.lock/x"), &[]));
    assert!(is_cargo_lock(&path("a/Cargo.lock")));
    // The generic TOML adapter still owns *.toml and not the lockfile.
    assert!(!TomlAdapter.matches(&path("Cargo.lock"), &[]));
    assert!(TomlAdapter.matches(&path("Cargo.toml"), &[]));
    // ADR 0013 amendment: its own language id, distinct from TOML's.
    assert_eq!(a.lang().as_str(), hord_lang_rust::CARGO_LOCK_LANG);
    assert_ne!(a.lang(), TomlAdapter.lang());
    assert!(a.is_definition(&NodeKind::new("table_array_element")));
}

#[test]
fn real_lockfiles_are_lossless() {
    for (name, text) in fixtures() {
        let tree = CargoLockAdapter.parse(text.as_bytes()).expect(&name);
        assert_eq!(
            CargoLockAdapter.project(&tree).as_slice(),
            text.as_bytes(),
            "lossless {name}"
        );
        tree.check_concat()
            .unwrap_or_else(|e| panic!("{name}: {e}"));
    }
}

#[test]
fn packages_are_named_by_package_id() {
    for (name, text) in fixtures() {
        let tree = CargoLockAdapter.parse(text.as_bytes()).expect(&name);
        let names = def_names(&tree, "table_array_element");
        let blocks = text.matches("[[package]]").count();
        assert_eq!(names.len(), blocks, "{name}: every package is named");
        let unique: BTreeSet<_> = names.iter().collect();
        assert_eq!(
            unique.len(),
            names.len(),
            "{name}: package names are unique"
        );
        assert!(names.iter().all(|n| n.starts_with("package::")));
    }
    let text = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.0", &[])]);
    let tree = CargoLockAdapter.parse(text.as_bytes()).unwrap();
    let packages = def_names(&tree, "table_array_element");
    assert!(packages.contains(&"package::serde".to_owned()));
    assert!(packages.contains(&"package::app".to_owned()));
    let pairs = def_names(&tree, "pair");
    assert!(pairs.contains(&"package::serde::checksum".to_owned()));
    // A second version lengthens both names to include the version.
    let text = lockfile(&[
        root("app", &["syn 1.0.0", "syn 2.0.0"]),
        pkg("syn", "1.0.0", &[]),
        pkg("syn", "2.0.0", &[]),
    ]);
    let tree = CargoLockAdapter.parse(text.as_bytes()).unwrap();
    let packages = def_names(&tree, "table_array_element");
    assert!(packages.contains(&"package::syn 1.0.0".to_owned()));
    assert!(packages.contains(&"package::syn 2.0.0".to_owned()));
}

#[test]
fn package_name_is_independent_of_position() {
    let one = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.0", &[])]);
    let two = lockfile(&[
        root("app", &["anyhow", "serde"]),
        pkg("anyhow", "1.0.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    let serde_of = |text: &str| {
        let tree = CargoLockAdapter.parse(text.as_bytes()).unwrap();
        tree.iter()
            .find(|(_, n)| {
                n.name
                    .as_ref()
                    .is_some_and(|q| q.to_string() == "package::serde")
            })
            .map(|(_, n)| n.normalized)
            .expect("serde package")
    };
    // Same name and content, even though it moved from index 1 to index 2.
    assert_eq!(serde_of(&one), serde_of(&two));
}

#[test]
fn ambiguous_versions_are_named_with_source() {
    let git = "git+https://github.com/serde-rs/serde?branch=main#0123abcd";
    let text = format!(
        "{HEADER}[[package]]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \
         \"serde 1.0.0 ({REGISTRY})\",\n \"serde 1.0.0 (git+https://github.com/serde-rs/serde?branch=main)\",\n]\n\n\
         {}[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"{git}\"\n",
        pkg("serde", "1.0.0", &[])
    );
    let tree = CargoLockAdapter.parse(text.as_bytes()).unwrap();
    let names = def_names(&tree, "table_array_element");
    assert!(names.contains(&format!("package::serde 1.0.0 {REGISTRY}")));
    assert!(names.contains(&format!("package::serde 1.0.0 {git}")));
    // Cargo's own spelling and order round-trip.
    assert_eq!(merge(&text, &text, &text).unwrap(), text);
}

// ------------------------------------------------------------------ merge

#[test]
fn unchanged_merge_is_byte_identical_on_real_lockfiles() {
    for (name, text) in fixtures() {
        let merged = merge(&text, &text, &text).expect(&name);
        assert!(
            merged == text,
            "{name}: re-emission differs from Cargo's bytes"
        );
    }
}

/// M3 acceptance: two sides each add a new package and list it in the root
/// package's dependencies.
#[test]
fn concurrent_dependency_additions_merge_cleanly() {
    let base = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let ours = lockfile(&[
        root("app", &["anyhow", "log"]),
        pkg("anyhow", "1.0.0", &[]),
        pkg("log", "0.4.0", &[]),
    ]);
    let theirs = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    let want = lockfile(&[
        pkg("anyhow", "1.0.0", &[]),
        root("app", &["anyhow", "log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want.clone()));
    let tree = CargoLockAdapter.parse(want.as_bytes()).unwrap();
    assert_eq!(CargoLockAdapter.project(&tree).as_slice(), want.as_bytes());
}

#[test]
fn additions_with_shared_transitive_dependency() {
    // Both sides pull in `itoa` through different new crates.
    let base = lockfile(&[root("app", &[])]);
    let ours = lockfile(&[
        root("app", &["ryu"]),
        pkg("itoa", "1.0.0", &[]),
        pkg("ryu", "1.0.0", &["itoa"]),
    ]);
    let theirs = lockfile(&[
        root("app", &["serde_json"]),
        pkg("itoa", "1.0.0", &[]),
        pkg("serde_json", "1.0.0", &["itoa"]),
    ]);
    let want = lockfile(&[
        root("app", &["ryu", "serde_json"]),
        pkg("itoa", "1.0.0", &[]),
        pkg("ryu", "1.0.0", &["itoa"]),
        pkg("serde_json", "1.0.0", &["itoa"]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

#[test]
fn addition_and_removal_compose() {
    let base = lockfile(&[
        root("app", &["log", "rand"]),
        pkg("log", "0.4.0", &[]),
        pkg("rand", "0.8.0", &[]),
    ]);
    let ours = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let theirs = lockfile(&[
        root("app", &["log", "rand", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("rand", "0.8.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    let want = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

#[test]
fn second_version_respells_dependencies() {
    // Ours adds a second `syn`; `syn` alone becomes ambiguous and Cargo
    // spells both with versions.
    let base = lockfile(&[root("app", &["syn"]), pkg("syn", "2.0.0", &[])]);
    let ours = lockfile(&[
        root("app", &["syn 1.0.0", "syn 2.0.0"]),
        pkg("syn", "1.0.0", &[]),
        pkg("syn", "2.0.0", &[]),
    ]);
    let theirs = lockfile(&[
        root("app", &["log", "syn"]),
        pkg("log", "0.4.0", &[]),
        pkg("syn", "2.0.0", &[]),
    ]);
    let want = lockfile(&[
        root("app", &["log", "syn 1.0.0", "syn 2.0.0"]),
        pkg("log", "0.4.0", &[]),
        pkg("syn", "1.0.0", &[]),
        pkg("syn", "2.0.0", &[]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

#[test]
fn packages_sort_by_semver_not_text() {
    let base = lockfile(&[root("app", &[])]);
    let ours = lockfile(&[root("app", &["foo 0.9.0"]), pkg("foo", "0.9.0", &[])]);
    let ours = ours.replace("\"foo 0.9.0\"", "\"foo\"");
    let theirs = lockfile(&[root("app", &["foo"]), pkg("foo", "0.10.0", &[])]);
    let merged = merge(&base, &ours, &theirs);
    // Both sides point `app` at a different `foo`: a real conflict.
    assert!(matches!(merged, Err(CargoLockMergeError::Conflict(_))));

    let theirs = lockfile(&[
        root("app", &[]),
        root("lib", &["foo"]),
        pkg("foo", "0.10.0", &[]),
    ]);
    let got = merge_both(&base, &ours, &theirs).unwrap();
    let nine = got.find("version = \"0.9.0\"").unwrap();
    let ten = got.find("version = \"0.10.0\"").unwrap();
    assert!(nine < ten, "0.9.0 sorts before 0.10.0");
}

#[test]
fn version_conflict_is_reported() {
    let base = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.0", &[])]);
    let ours = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.1", &[])]);
    let theirs = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.2", &[])]);
    let conflicts = merge_both(&base, &ours, &theirs).unwrap_err();
    assert_eq!(
        conflicts[0],
        CargoLockConflict::Toml(TomlConflict {
            path: "package[serde].version".into(),
            kind: ConflictKind::BothChanged,
        })
    );
    // Both sides adding a crate at different versions for one dependent is
    // also reported.
    let base = lockfile(&[root("app", &[])]);
    let ours = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.1", &[])]);
    let theirs = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.2", &[])]);
    let conflicts = merge_both(&base, &ours, &theirs).unwrap_err();
    assert!(matches!(
        conflicts.as_slice(),
        [CargoLockConflict::AmbiguousDependency { package, dependency }]
            if package == "app 0.1.0" && dependency == "serde"
    ));
}

#[test]
fn same_upgrade_on_both_sides_composes() {
    let base = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.0", &[])]);
    let both = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.1", &[])]);
    assert_eq!(merge_both(&base, &both, &both), Ok(both.clone()));
    // One side upgrades, the other adds an unrelated crate.
    let theirs = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    let want = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.1", &[]),
    ]);
    assert_eq!(merge_both(&base, &both, &theirs), Ok(want));
}

#[test]
fn field_and_delete_modify_conflicts() {
    let base = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let mut ours = base.clone();
    ours = ours.replacen(&format!("{:0>64}", 8), &format!("{:1>64}", 8), 1);
    let mut theirs = base.clone();
    theirs = theirs.replacen(&format!("{:0>64}", 8), &format!("{:2>64}", 8), 1);
    let conflict = |path: &str, kind| {
        CargoLockConflict::Toml(TomlConflict {
            path: path.into(),
            kind,
        })
    };
    assert_eq!(
        merge_both(&base, &ours, &theirs),
        Err(vec![conflict(
            "package[log].checksum",
            ConflictKind::BothChanged
        )])
    );
    let removed = lockfile(&[root("app", &[])]);
    assert_eq!(
        merge_both(&base, &ours, &removed),
        Err(vec![conflict("package[log]", ConflictKind::DeleteModify)])
    );
}

#[test]
fn dangling_dependency_is_a_conflict() {
    let base = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let ours = lockfile(&[root("app", &[])]);
    let theirs = lockfile(&[
        root("app", &["log"]),
        root("tool", &["log"]),
        pkg("log", "0.4.0", &[]),
    ]);
    let conflicts = merge_both(&base, &ours, &theirs).unwrap_err();
    assert!(matches!(
        conflicts.as_slice(),
        [CargoLockConflict::DanglingDependency { package, dependency }]
            if package == "tool 0.1.0" && dependency == "log"
    ));
}

#[test]
fn empty_base_means_both_added_the_file() {
    let ours = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let theirs = lockfile(&[root("app", &["serde"]), pkg("serde", "1.0.0", &[])]);
    let want = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    assert_eq!(merge_both("", &ours, &theirs), Ok(want));
}

#[test]
fn unsupported_inputs_are_reported_not_merged() {
    let good = lockfile(&[root("app", &[])]);
    let old = "[root]\nname = \"app\"\nversion = \"0.1.0\"\n";
    assert!(matches!(
        merge(old, &good, &good),
        Err(CargoLockMergeError::Unsupported { .. })
    ));
    let dangling = lockfile(&[root("app", &["nope"])]);
    assert!(matches!(
        merge(&good, &dangling, &good),
        Err(CargoLockMergeError::Unsupported { .. })
    ));
    assert!(matches!(
        merge(&good, "not = [toml", &good),
        Err(CargoLockMergeError::Unsupported { .. })
    ));
}

#[test]
fn upgrade_composes_with_other_side_edit() {
    // Ours bumps `cc`; theirs bumps `shlex`, which `cc` depends on by name.
    let base = lockfile(&[
        root("app", &["cc"]),
        pkg("cc", "1.2.35", &["shlex"]),
        pkg("shlex", "1.1.0", &[]),
    ]);
    let ours = lockfile(&[
        root("app", &["cc"]),
        pkg("cc", "1.2.36", &["shlex"]),
        pkg("shlex", "1.1.0", &[]),
    ]);
    let theirs = lockfile(&[
        root("app", &["cc"]),
        pkg("cc", "1.2.35", &["shlex"]),
        pkg("shlex", "1.3.0", &[]),
    ]);
    let want = lockfile(&[
        root("app", &["cc"]),
        pkg("cc", "1.2.36", &["shlex"]),
        pkg("shlex", "1.3.0", &[]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

#[test]
fn workspace_version_bump_composes_with_dependency_addition() {
    let bump = |deps: &[&str]| root("app", deps).replace("0.1.0", "0.2.0");
    let base = lockfile(&[root("app", &["log"]), pkg("log", "0.4.0", &[])]);
    let ours = lockfile(&[bump(&["log"]), pkg("log", "0.4.0", &[])]);
    let theirs = lockfile(&[
        root("app", &["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    let want = lockfile(&[
        bump(&["log", "serde"]),
        pkg("log", "0.4.0", &[]),
        pkg("serde", "1.0.0", &[]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

#[test]
fn name_spelled_dependency_is_respelled_when_it_becomes_ambiguous() {
    // Ours adds `syn 1.0.0`, so `syn` alone becomes ambiguous; theirs adds a
    // new dependent spelled `syn`, meaning 2.0.0.
    let base = lockfile(&[root("app", &["syn"]), pkg("syn", "2.0.0", &[])]);
    let ours = lockfile(&[
        root("app", &["syn 1.0.0", "syn 2.0.0"]),
        pkg("syn", "1.0.0", &[]),
        pkg("syn", "2.0.0", &[]),
    ]);
    let theirs = lockfile(&[
        root("app", &["syn"]),
        root("tool", &["syn"]),
        pkg("syn", "2.0.0", &[]),
    ]);
    let want = lockfile(&[
        root("app", &["syn 1.0.0", "syn 2.0.0"]),
        pkg("syn", "1.0.0", &[]),
        pkg("syn", "2.0.0", &[]),
        root("tool", &["syn 2.0.0"]),
    ]);
    assert_eq!(merge_both(&base, &ours, &theirs), Ok(want));
}

// ------------------------------------------------ real-lockfile proptests

/// A real lockfile with a set of uniquely named, source-bearing packages
/// removed as a new dependency would add them: the `[[package]]` block and
/// every `"name",` dependency line.
fn without(text: &str, names: &[&str]) -> String {
    let mut out = text.to_owned();
    for name in names {
        let start = out
            .find(&format!("[[package]]\nname = \"{name}\"\n"))
            .expect("package block");
        let end = out[start + 1..]
            .find("[[package]]")
            .map_or(out.len(), |i| start + 1 + i);
        out.replace_range(start..end, "");
        out = out.replace(&format!(" \"{name}\",\n"), "");
    }
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// Names that occur once in the lockfile and are depended on by name only.
fn removable(text: &str) -> Vec<String> {
    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for line in text.lines() {
        if let Some(name) = line
            .strip_prefix("name = \"")
            .and_then(|l| l.strip_suffix('"'))
        {
            *counts.entry(name).or_default() += 1;
        }
    }
    counts
        .into_iter()
        .filter(|(name, n)| {
            *n == 1
                && text.contains(&format!(" \"{name}\",\n"))
                && !text.contains(&format!(" \"{name} "))
        })
        .map(|(name, _)| name.to_owned())
        .collect()
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(24))]

    /// Both sides of a real lockfile each add different dependencies (new
    /// `[[package]]` blocks plus entries in their dependents' lists). The
    /// merge must reproduce Cargo's own bytes, in either order.
    #[test]
    fn real_lockfile_concurrent_additions_reproduce_it(
        pick in any::<prop::sample::Index>(),
        a in any::<prop::sample::Index>(),
        b in any::<prop::sample::Index>(),
    ) {
        let fixtures = fixtures();
        let (name, full) = &fixtures[pick.index(fixtures.len())];
        let names = removable(full);
        prop_assume!(names.len() >= 2);
        let (x, y) = (&names[a.index(names.len())], &names[b.index(names.len())]);
        prop_assume!(x != y);
        // Removing one must not also edit the other's block.
        let block = |n: &str| {
            let start = full.find(&format!("[[package]]\nname = \"{n}\"\n")).unwrap();
            let end = full[start + 1..].find("[[package]]").map_or(full.len(), |i| start + 1 + i);
            full[start..end].to_owned()
        };
        prop_assume!(!block(x).contains(&format!(" \"{y}\",")));
        prop_assume!(!block(y).contains(&format!(" \"{x}\",")));
        let base = without(full, &[x, y]);
        let ours = without(full, &[y]);
        let theirs = without(full, &[x]);
        let merged = merge_both(&base, &ours, &theirs);
        prop_assert!(merged.as_ref() == Ok(full), "{name}: adding {x} and {y}");
    }
}

/// Small random lockfiles over a fixed package pool, for commutativity.
fn arb_lock() -> impl Strategy<Value = String> {
    const POOL: [(&str, &str); 6] = [
        ("anyhow", "1.0.0"),
        ("log", "0.4.0"),
        ("serde", "1.0.0"),
        ("serde", "1.0.1"),
        ("syn", "1.0.0"),
        ("syn", "2.0.0"),
    ];
    (
        prop::collection::vec(any::<bool>(), POOL.len()),
        prop::collection::vec(any::<bool>(), POOL.len()),
        prop::collection::vec(0u8..2, POOL.len()),
    )
        .prop_map(|(present, root_dep, checksum)| {
            let keep: Vec<usize> = (0..POOL.len()).filter(|&i| present[i]).collect();
            let root_deps: Vec<String> = keep
                .iter()
                .filter(|&&i| root_dep[i])
                .map(|&i| format!("{} {}", POOL[i].0, POOL[i].1))
                .collect();
            let root_deps: Vec<&str> = root_deps.iter().map(String::as_str).collect();
            let mut blocks = vec![root("app", &root_deps)];
            for i in keep {
                let (name, version) = POOL[i];
                let block = pkg(name, version, &[]);
                blocks.push(if checksum[i] == 0 {
                    block
                } else {
                    block.replace("checksum = \"0", "checksum = \"f")
                });
            }
            lockfile(&blocks)
        })
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    #[test]
    fn merge_is_commutative(base in arb_lock(), ours in arb_lock(), theirs in arb_lock()) {
        // merge_both asserts commutativity of both results and conflicts.
        if let Ok(merged) = merge_both(&base, &ours, &theirs) {
            let tree = CargoLockAdapter.parse(merged.as_bytes()).expect("re-parses");
            let projected = CargoLockAdapter.project(&tree);
            prop_assert_eq!(projected.as_slice(), merged.as_bytes());
            // Idempotent: merging the result with itself changes nothing.
            prop_assert_eq!(merge(&merged, &merged, &merged).unwrap(), merged);
        }
    }

    #[test]
    fn one_sided_change_is_taken_verbatim(base in arb_lock(), ours in arb_lock()) {
        let canon = |s: &str| merge(s, s, s).unwrap();
        prop_assert_eq!(merge(&base, &ours, &base).unwrap(), canon(&ours));
        prop_assert_eq!(merge(&base, &base, &ours).unwrap(), canon(&ours));
    }
}
